#!/usr/bin/env python3

# Using pipreqs module to generate requirements.txt file automatically

import asyncio
from forte.client import ForteClient

async def main():
    client = ForteClient()
    await client.connect('127.0.0.1')
    await client.request()

if __name__ == '__main__':
    asyncio.run(main())